### ISSUE TITLE
How to add a missing app?

### ISSUE THREAD

**Issue by gramster** [meta-dog/meta-dog#39]
For example, Hellsweeper VR is out but is not in the table.

**Comment by davidciglesias** [comment]
Hey! :) 

You can simply paste the links on the popup that appears when pressing "+" in the App section

![image](https://github.com/meta-dog/meta-dog/assets/15752156/d6e1cbd2-80d0-4021-a694-65b39251d077)

Please bear in mind that the verification process takes some time (especially since lately they keep modifying the login & website 😄 )

**Comment by gramster** [comment]
I tried that yesterday for Hellsweeper. I assume by that you mean pasting
in a full referral link to the app. It got added to the queue but the app
never appeared.

**Comment by davidciglesias** [comment]
I've refreshed the verification manually (it got stuck in a new 2FA step that apparently they just implemented... great) so you should see this now 😄
